error: style error message
markup:
- use class names for button and text
- use aria-label for button
- use symmetric x for button text

styles:
- move back to top to match markup
- absolutely position button
- use text color with borders instead of background-color